JobBoardMVC/Controllers/CompanyInfoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JobBoardMVC.Models;
using Microsoft.AspNet.Identity;
using JobBoardMVC.CustomFilters;
using System.Threading.Tasks;
using System.Drawing;

namespace JobBoardMVC
{
    public class CompanyInfoController : Controller
    {
        private JobBoardMvcContext db = new JobBoardMvcContext();

		public ActionResult Index(int id)
		{
			var fileToRetrieve = db.CompanyFiles.Find(id);
			return File(fileToRetrieve.Content, fileToRetrieve.ContentType);
		}

		public ActionResult Details(string id)
        {
            var model = new CompanyViewModel();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            model.company = db.Companies.Include(c => c.Files).SingleOrDefault(c => c.CompanyName == id);
            if (model.company == null)
            {
                return HttpNotFound();
            }
            // model.jobs
            model.jobs = db.Jobs.Where(j => j.CompanyCompanyName == model.company.CompanyName).ToList();
            //<List>model.jobs = <List>db.Jobs.Where(j => j.CompanyCompanyName == model.company.CompanyName);

            model.jobCount = model.jobs.ToList().Count;

            // check if this company has already been saved by this user
            var userID = Guid.Parse(User.Identity.GetUserId());
            var saved = db.SavedCompanies.Where(s => s.CompanyCompanyName == model.company.CompanyName && s.UserID == userID).FirstOrDefault();
            model.companySaved = (saved == null ? false : true);

            // Create a list of jobIDs where the userID equals the current user
            // from the SavedJobs table. This is used to evaluate whether or not the
            // save button should be enabled or disabled in the company info results.
            IEnumerable<SavedJob> savedJobsView = db.SavedJobs.Where(s => s.UserID.Equals(userID));
            var usersSavedJobIDs = savedJobsView.Select(s => s.JobID).ToList();
            ViewBag.usersSavedJobIDs = usersSavedJobIDs;

            return View(model);
        }


		// GET: CompanyInfo/Create
		[CustomAuthorize(Roles = "Admin")]
		public ActionResult Create()
		{
			return View();
		}

		// POST: CompanyInfo/Create
		// To protect from overposting attacks, please enable the specific properties you want to bind to, for
		// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[CustomAuthorize(Roles = "Admin")]
		[ValidateAntiForgeryToken]
		public async Task<ActionResult> Create([Bind(Include = "CompanyName,CompanyLink,Address,City,State,ZipCode,Latitude,Longitude,CareerPage,CompanyType,IndustryServed,LanguagesUsed,Files")] Company company, HttpPostedFileBase upload)
		{
			var _company = db.Companies.Find(company.CompanyName);
			if (_company != null)
			{
				ViewBag.ErrorMessage = company.CompanyName + " already exists.";
			}
			else if (ModelState.IsValid)
			{
				if (upload != null && upload.ContentLength > 0)
				{
					var logo = new CompanyFile
					{
						FileName = System.IO.Path.GetFileName(upload.FileName),
						FileType = FileType.Logo,
						ContentType = upload.ContentType,
						CompanyName = company.CompanyName
					};
					using (var reader = new System.IO.BinaryReader(upload.InputStream))
					{
						logo.Content = reader.ReadBytes(upload.ContentLength);
					}
					company.Files = new List<CompanyFile> { logo };
				}
				db.Companies.Add(company);
				await db.SaveChangesAsync();
				return RedirectToAction("Details", new { id = company.CompanyName });
			}

			return View(company);
		}

		//GET: Jobs/Edit/5
		[CustomAuthorize(Roles = "Admin")]
		public ActionResult Edit(string id)
		{
			var company = new Company();
			if (id == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			company = db.Companies.Include(c => c.Files).SingleOrDefault(c => c.CompanyName == id);
			if (company == null)
			{
				return HttpNotFound();
			}
			return View(company);
		}

		// POST: Jobs/Edit/5
		[HttpPost]
		[CustomAuthorize(Roles = "Admin")]
		[ValidateAntiForgeryToken]
		public ActionResult Edit(string id, HttpPostedFileBase upload)
		{
			if (id == null)
			{
				return HttpNotFound();
			}
			var companyToUpdate = db.Companies.Find(id);
			try
			{
				if (upload != null && upload.ContentLength > 0)
				{
					var oldLogo = companyToUpdate.Files.Any(f => f.FileType == FileType.Logo);
					if (oldLogo == true)
					{
						db.CompanyFiles.Remove(companyToUpdate.Files.First(f => f.FileType == FileType.Logo));
					}
					var logo = new CompanyFile
					{
						FileName = System.IO.Path.GetFileName(upload.FileName),
						FileType = FileType.Logo,
						ContentType = upload.ContentType,
						CompanyName = companyToUpdate.CompanyName
					};
					using (var reader = new System.IO.BinaryReader(upload.InputStream))
					{
						logo.Content = reader.ReadBytes(upload.ContentLength);
					}
					companyToUpdate.Files = new List<CompanyFile> { logo };
				}
				if (ModelState.IsValid && TryUpdateModel(companyToUpdate, new string[] { "CompanyName", "CompanyLink", "Address", "City", "State", "ZipCode", "Latitude", "Longitude", "CareerPage", "CompanyType", "IndustryServed", "LanguagesUsed", "Files" }))
				{
					try
					{
						db.SaveChanges();
						return RedirectToAction("Details", new { id = companyToUpdate.CompanyName });
					}
					catch (DataException /*ex*/)
					{
						ModelState.AddModelError("", "Unable to save changes.");
					}
				}
			}
			catch (Exception ex)
			{
				throw ex;
			}

			return View(companyToUpdate);
		}

		//original Edit method - wasn't saving changes to the database (logo part was working though...)
		// To protect from overposting attacks, please enable the specific properties you want to bind to, for
		// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
		//[HttpPost]
		//[CustomAuthorize(Roles = "Admin")]
		//[ValidateAntiForgeryToken]
		//public ActionResult Edit([Bind(Include = "CompanyName,CompanyLink,Address,City,State,ZipCode,Latitude,Longitude,CareerPage,Files")] Company company, HttpPostedFileBase upload)
		//{
		//          if (company == null)
		//          {
		//              return HttpNotFound();
		//          }
		//          try
		//          {
		//		Company _company = db.Companies.Find(company.CompanyName);
		//		if (upload != null && upload.ContentLength > 0)
		//		{
		//			var oldLogo = _company.Files.Any(f => f.FileType == FileType.Logo);
		//			if (oldLogo == true)
		//			{
		//				db.CompanyFiles.Remove(_company.Files.First(f => f.FileType == FileType.Logo));
		//			}
		//			var logo = new CompanyFile
		//			{
		//				FileName = System.IO.Path.GetFileName(upload.FileName),
		//				FileType = FileType.Logo,
		//				ContentType = upload.ContentType,
		//				CompanyName = company.CompanyName
		//			};
		//			using (var reader = new System.IO.BinaryReader(upload.InputStream))
		//			{
		//				logo.Content = reader.ReadBytes(upload.ContentLength);
		//			}
		//			company.Files = new List<CompanyFile> { logo };
		//		}

		//		if (ModelState.IsValid)
		//              {

		//			db.Entry(company).State = EntityState.Modified;
		//                  db.SaveChanges();
		//                  return RedirectToAction("Details", new { id = company.CompanyName });
		//              }
		//          }
		//          catch (Exception ex)
		//          {

		//              throw ex;
		//          }

		//	return View(company);
		//}


		protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

JobBoardMVC/Controllers/JobsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JobBoardMVC.Models;
using System.Data.Entity.Migrations;
using JobBoardMVC.CustomFilters;
using Microsoft.AspNet.Identity;

namespace JobBoardMVC.Controllers
{
    public class JobsController : Controller
    {
        private JobBoardMvcContext context = new JobBoardMvcContext();

        // GET: Jobs
  
        public async Task<ActionResult> Index(string jobTitleString, string companyString, int selectedLocationId = 0, int JobID = 0)
        {
            // Include LINQ queries to allow filters
            var jobs = from j in context.Jobs
                       select j;

            // adding a var for counting number of companies used below in company count
            var companies = from c in context.Companies
                       select c;
            

            // Job title search form field
            if (!String.IsNullOrEmpty(jobTitleString))
            {
                jobs = jobs.Where(j => j.JobTitle.Contains(jobTitleString));
            }

            // company search form field
            if (!String.IsNullOrEmpty(companyString))
            {
                jobs = jobs.Where(j => j.CompanyCompanyName.Contains(companyString));
            }

            // grab a count of the number of jobs currently inside the jobs variable.
            int count = jobs.Count();
            // store it in viewbag for the View to display
            ViewBag.Counts = count;

            // Set JobID for indication whether Index action was called from Save action
            ViewBag.JobID = JobID;


            // Need for company count
            if (!String.IsNullOrEmpty(companyString))
            {
                companies = companies.Where(c => c.CompanyName.Contains(companyString));
            }
            // Grab a count of the number of companies inside the companies variable
            int companyCount = companies.Count();
            // store it in viewbag for the View to display
            ViewBag.companyCount = companyCount;

            // Create a list of jobIDs where the userID equals the current user
            // from the SavedJobs table. This is used to evaluate whether or not the
            // save button should be enabled or disabled in the job search results.
            if (User.Identity.GetUserId() != null)
            {
                var userID = Guid.Parse(User.Identity.GetUserId());
                IEnumerable<SavedJob> savedJobsView = context.SavedJobs.Where(s => s.UserID.Equals(userID));
                var usersSavedJobIDs = savedJobsView.Select(s => s.JobID).ToList();
                ViewBag.usersSavedJobIDs = usersSavedJobIDs;
            }


            //instantiate the view model and serve it to the view

            var jobLocationVM = new JobLocationViewModel();
            jobLocationVM.jobs = await jobs.ToListAsync();

            return View(jobLocationVM);
        }

        // GET: Jobs/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Job job = await context.Jobs.FindAsync(id);
            if (job == null)
            {
                return HttpNotFound();
            }
            return View(job);
        }

        // GET: Jobs/Create
        [CustomAuthorize(Roles = "Admin")]
        public ActionResult Create()
        {
			PopulateCompanyDropdownList();
			return View();
        }

        // POST: Jobs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [CustomAuthorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "ID,ApplicationLink,Company,DatePosted,Experience,Hours,JobID,JobTitle,LanguagesUsed,Location,Salary")] Job job)
        {
            if (ModelState.IsValid)
            {
                context.Jobs.Add(job);
                await context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
			PopulateCompanyDropdownList();
			return View(job);
        }

        //GET: Jobs/Edit/5
        [CustomAuthorize(Roles = "Admin")]
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Job job = await context.Jobs.FindAsync(id);
            if (job == null)
            {
                return HttpNotFound();
            }
			PopulateCompanyDropdownList();
			return View(job);
        }

        // POST: Jobs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [CustomAuthorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "ID,ApplicationLink,Company,DatePosted,Experience,Hours,JobID,JobTitle,LanguagesUsed,Location,Salary")] Job job)
        {
            if (ModelState.IsValid)
            {
                context.Entry(job).State = EntityState.Modified;
                await context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
			PopulateCompanyDropdownList();
			return View(job);
        }

		private void PopulateCompanyDropdownList()
		{
			var companies = new List<string>();
			var companyQuery = from c in context.Companies
							   orderby c.CompanyName
							   select c.CompanyName;
			companies.AddRange(companyQuery.Distinct());
			ViewBag.Companies = new SelectList(companies);
		}

		//GET: Jobs/Delete/5
		[CustomAuthorize(Roles = "Admin")]
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Job job = await context.Jobs.FindAsync(id);
            if (job == null)
            {
                return HttpNotFound();
            }
            return View(job);
        }

        //public ActionResult Delete()
        //{
        //    return View();
        //}

        // POST: Jobs/Delete/5
        [HttpPost, ActionName("Delete")]
        [CustomAuthorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Job job = await context.Jobs.FindAsync(id);
            context.Jobs.Remove(job);
            await context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                context.Dispose();
            }
            base.Dispose(disposing);
        }

        // Save - this action takes a jobId value passed to it from a save button on the index page
        //        then adds the associated JobID, UserId, applicationLink, Company, and JobTitle information
        //        to the SavedJobs table. It is called via ajax from the page, so it doesn't return a 
        //        view. It's possible, therefore, that the syntax of the action method should be changed
        //        at some point.
        
        [HttpPost]
        [Authorize]
        public async Task<ActionResult> Save(int? jobId)
        {
            if (jobId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Job job = await context.Jobs.FindAsync(jobId);
            if (job == null)
            {
                return HttpNotFound();
            }


            var userID = Guid.Parse(User.Identity.GetUserId());
            
            if (ModelState.IsValid)
            {
                var savedJob = new SavedJob();
                savedJob.JobID = job.JobID;
                savedJob.UserID = userID;
                savedJob.ApplicationLink = job.ApplicationLink;
                savedJob.CompanyCompanyName = job.CompanyCompanyName;
                savedJob.JobTitle = job.JobTitle;
                savedJob.DatePosted = job.DatePosted;
                savedJob.DateSaved = DateTime.Now;
                savedJob.Location = job.Location;
                context.SavedJobs.Add(savedJob);
                await context.SaveChangesAsync();
            }

            return RedirectToAction("Index");
        }

        /*
        // CompanyInfo - 
        // CompanyName value is passed from index page, linked to Company.Id 
        // then builds a new tabbed page with CompanyName, Address, Map information
 
        [Authorize]
        public async Task<ActionResult> CompanyInfo(int? Id)
        {
            if (Id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Company company = await context.Companies.FindAsync(Id);
            if (company == null)
            {
                return HttpNotFound();
            }
            
            if (ModelState.IsValid)
            {
                //do we need a new model for the CompanyInfo Page?
                /*
                var company = new SavedJob();
                savedJob.UserID = userID;
                savedJob.ApplicationLink = job.ApplicationLink;
                savedJob.Company = job.CompanyName;
                savedJob.JobTitle = job.JobTitle;
                context.SavedJobs.Add(savedJob);
                await context.SaveChangesAsync();

JobBoardMVC/Views/CompanyInfo/Create.cshtml
@model JobBoardMVC.Models.Company

@{
	Layout = "../Shared/_Layout.cshtml";
}

@* Page used to add a new company to the database.
   Part of the CRUD operation. This page is restricted to only Admin users.*@
<!DOCTYPE html>

<html>
<head>
	<meta name="viewport" content="width=device-width, user-scalable=no, maximum-scale=1.0, initial-scale=1.0">

	<title>Create</title>
</head>
<body>
	@Scripts.Render("~/bundles/jquery")
	@Scripts.Render("~/bundles/jqueryval")

	@using (Html.BeginForm("Create", "CompanyInfo", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
	{
		@Html.AntiForgeryToken()

		<div class="form-horizontal">
			<h4>Add a New Company</h4>
			<p style="color:red;">@ViewBag.ErrorMessage</p>
			<hr />
			@Html.ValidationSummary(true, "", new { @class = "text-danger" })
			<div class="form-group">
				@Html.LabelFor(model => model.CompanyName, htmlAttributes: new { @class = "control-label col-md-2" })
				<div class="col-md-10">
					@Html.EditorFor(model => model.CompanyName, new { htmlAttributes = new { @class = "form-control" } })
					@Html.ValidationMessageFor(model => model.CompanyName, "", new { @class = "text-danger" })
				</div>
			</div>

			<div class="form-group">
				@Html.LabelFor(model => model.CompanyLink, htmlAttributes: new { @class = "control-label col-md-2" })
				<div class="col-md-10">
					@Html.EditorFor(model => model.CompanyLink, new { htmlAttributes = new { @class = "form-control" } })
					@Html.ValidationMessageFor(model => model.CompanyLink, "", new { @class = "text-danger" })
				</div>
			</div>

			<div class="form-group">
				@Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
				<div class="col-md-10">
					@Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
					@Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
				</div>
			</div>

			<div class="form-group">
				@Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
				<div class="col-md-10">
					@Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
					@Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
				</div>
			</div>

			<div class="form-group">
				@Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-2" })
				<div class="col-md-10">
					@Html.EditorFor(model => model.State, new { htmlAttributes = new { @class = "form-control" } })
					@Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
				</div>
			</div>

			<div class="form-group">
				@Html.LabelFor(model => model.ZipCode, htmlAttributes: new { @class = "control-label col-md-2" })
				<div class="col-md-10">
					@Html.EditorFor(model => model.ZipCode, new { htmlAttributes = new { @class = "form-control" } })
					@Html.ValidationMessageFor(model => model.ZipCode, "", new { @class = "text-danger" })
				</div>
			</div>

			<div class="form-group">
				@Html.LabelFor(model => model.Latitude, htmlAttributes: new { @class = "control-label col-md-2" })
				<div class="col-md-10">
					@Html.EditorFor(model => model.Latitude, new { htmlAttributes = new { @class = "form-control" } })
					@Html.ValidationMessageFor(model => model.Latitude, "", new { @class = "text-danger" })
				</div>
			</div>

			<div class="form-group">
				@Html.LabelFor(model => model.Longitude, htmlAttributes: new { @class = "control-label col-md-2" })
				<div class="col-md-10">
					@Html.EditorFor(model => model.Longitude, new { htmlAttributes = new { @class = "form-control" } })
					@Html.ValidationMessageFor(model => model.Longitude, "", new { @class = "text-danger" })
				</div>
			</div>

			<div class="form-group">
				@Html.LabelFor(model => model.CareerPage, htmlAttributes: new { @class = "control-label col-md-2" })
				<div class="col-md-10">
					@Html.EditorFor(model => model.CareerPage, new { htmlAttributes = new { @class = "form-control" } })
					@Html.ValidationMessageFor(model => model.CareerPage, "", new { @class = "text-danger" })
				</div>
			</div>

			<div class="form-group">
				@Html.LabelFor(model => model.CompanyType, htmlAttributes: new { @class = "control-label col-md-2" })
				<div class="col-md-10">
					@Html.EditorFor(model => model.CompanyType, new { htmlAttributes = new { @class = "form-control" } })
					@Html.ValidationMessageFor(model => model.CompanyType, "", new { @class = "text-danger" })
				</div>
			</div>

			<div class="form-group">
				@Html.LabelFor(model => model.IndustryServed, htmlAttributes: new { @class = "control-label col-md-2" })
				<div class="col-md-10">
					@Html.EditorFor(model => model.IndustryServed, new { htmlAttributes = new { @class = "form-control" } })
					@Html.ValidationMessageFor(model => model.IndustryServed, "", new { @class = "text-danger" })
				</div>
			</div>

			<div class="form-group">
				@Html.LabelFor(model => model.LanguagesUsed, htmlAttributes: new { @class = "control-label col-md-2" })
				<div class="col-md-10">
					@Html.EditorFor(model => model.LanguagesUsed, new { htmlAttributes = new { @class = "form-control" } })
					@Html.ValidationMessageFor(model => model.LanguagesUsed, "", new { @class = "text-danger" })
				</div>
			</div>

            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.Description, new { @class = "form-control", rows = "3" })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>

			<div class="form=group">
				@Html.Label("Logo", new { @class = "control-label col-md-2" })
				<div class="col-md-10">
					<input type="file" id="Logo" name="upload" />
				</div>
			</div>

			<div class="form-group">
				<div class="col-md-offset-2 col-md-10">
					&nbsp; &nbsp;<input type="submit" value="Create" class="btn btn-primary" />
				</div>
			</div>
		</div>
	}

	<div class="control-label col-md-3" style="padding-left: 60px;">
		@Html.ActionLink("Back to Dashboard", "Admin", "Home")
	</div>
</body>
</html>

JobBoardMVC/Views/CompanyInfo/Delete.cshtml
@model JobBoardMVC.Models.Company

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Company</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CompanyLink)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CompanyLink)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ZipCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ZipCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Latitude)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Latitude)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Longitude)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Longitude)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CareerPage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CareerPage)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index", "Jobs")
        </div>
    }
</div>

JobBoardMVC/Views/CompanyInfo/Index.cshtml
@*@model IEnumerable<JobBoardMVC.Models.Company>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CompanyLink)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.City)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.State)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ZipCode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Latitude)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Longitude)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CareerPage)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CompanyLink)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Address)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.City)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.State)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ZipCode)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Latitude)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Longitude)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CareerPage)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.CompanyName }) |
            @Html.ActionLink("Details", "Details", new { id=item.CompanyName }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.CompanyName })
        </td>
        var latlng = new google.maps.LatLng(@ViewBag.lat, @ViewBag.lng)
    </tr>
}

</table>*@